version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - pip install awscli --upgrade --user
      - echo `aws --version`
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ${region} --no-include-email)
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Writing image definitions file...
      - printf '[{"name":"web","imageUri":"%s"}]' ${repository_url}:latest > imagedefinitions.json
      - echo upgrading db-migrate task definitions
      - aws ecs run-task --launch-type FARGATE --region ${region} --cluster ${cluster_name} --task-definition ${environment}_db_migrate --network-configuration "awsvpcConfiguration={subnets=[${subnet_id}],securityGroups=[${security_group_ids}]}"
artifacts:
  files: imagedefinitions.json